version: "2"

services:
  db:
    image: postgres:latest
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASS=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    image : lequal/sonarqube:latest
    #build: .
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    ports:
      - "9000:9000"

networks :
  sonarnet:
    driver: bridge
volumes:
  postgresql:
  postgresql_data:
